data:
  raw_dir: data/raw
  processed_dir: data/processed
  passages: data/processed/passages.parquet
index:
  out_dir: index
  faiss_index: index/faiss.index
  embed_meta: index/embed_meta.parquet
  bm25_tokens: index/bm25_tokens.npy
  pid_map: index/pid_map.parquet
models:
  embedder: sentence-transformers/all-MiniLM-L6-v2
  reranker: cross-encoder/ms-marco-MiniLM-L-6-v2
retrieval:
  bm25_topn: 200
  embed_topn: 200
  final_k: 10
  rrf_k: 60
generator:
  max_claims: 6
  cite_each_claim: true
eval:
  topics: [battery, screen, display, camera, sound, audio, noise, durability, charging, fit, comfort, performance, speed]
  k_list: [1,3,5,10]
